'use client';
import {useEffect,useState} from 'react';import {Nav} from '../components/Nav';import {api,upload} from '../lib/api';
export default function Dashboard(){const [projects,setProjects]=useState<any[]>([]);const [title,setTitle]=useState('My MSc Thesis');const [active,setActive]=useState<any>(null);const [file,setFile]=useState<File|null>(null);const [task,setTask]=useState('Generate a literature review and research gaps from uploaded papers.');const [agent,setAgent]=useState('literature_review');const [output,setOutput]=useState('');
async function load(){try{setProjects(await api('/projects'))}catch{}}
useEffect(()=>{load()},[]);
async function create(){const p=await api('/projects',{method:'POST',body:JSON.stringify({title,kind:'thesis',owner_id:'demo-user'})});setActive(p);await load()}
async function doUpload(){if(active&&file){await upload(active.id,file);alert('Uploaded and chunked')}}
async function run(){if(!active)return alert('Create/select a project first');const r=await api('/agents/run',{method:'POST',body:JSON.stringify({project_id:active.id,agent_type:agent,task})});setOutput(r.output)}
return <><Nav/><main className="max-w-6xl mx-auto px-6 py-8 grid lg:grid-cols-3 gap-6"><section className="card p-6"><h2 className="font-black text-2xl mb-4">Projects</h2><input className="input mb-3" value={title} onChange={e=>setTitle(e.target.value)}/><button className="btn btn-primary w-full" onClick={create}>Create Project</button><div className="mt-5 space-y-2">{projects.map(p=><button className="block w-full text-left border rounded-xl p-3" key={p.id} onClick={()=>setActive(p)}>{p.title}<br/><span className="text-xs text-slate-500">{p.kind}</span></button>)}</div></section><section className="card p-6 lg:col-span-2"><h2 className="font-black text-2xl">Workspace {active?`— ${active.title}`:''}</h2><div className="mt-5 grid md:grid-cols-2 gap-4"><div><label className="font-bold">Upload PDF / TXT</label><input className="input mt-2" type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="btn border mt-3" onClick={doUpload}>Upload</button></div><div><label className="font-bold">Agent</label><select className="input mt-2" value={agent} onChange={e=>setAgent(e.target.value)}><option value="literature_review">Literature Review</option><option value="thesis_supervisor">Thesis Supervisor</option><option value="paper_writer">Paper Writer</option><option value="reviewer">Reviewer</option><option value="rebuttal">Rebuttal</option><option value="expose">Exposé</option><option value="statistics">Statistics</option><option value="latex">LaTeX</option></select></div></div><textarea className="input mt-4 h-28" value={task} onChange={e=>setTask(e.target.value)}/><button className="btn btn-primary mt-3" onClick={run}>Run Agent</button><pre className="mt-5 whitespace-pre-wrap bg-slate-950 text-slate-50 rounded-2xl p-5 overflow-auto min-h-64">{output||'Agent output will appear here.'}</pre></section></main></>}
